sonar.projectKey=LuisSebas060104_lab6
sonar.organization=luissebas060104
sonar.projectName=lab6_software
sonar.projectVersion=1.0
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
